mv "1. Two Sum.py" "0001. Two Sum.py"
mv "12. Integer to Roman.py" "0012. Integer to Roman.py"
mv "2. Add Two Numbers.py" "0002. Add Two Numbers.py"
mv "202. Happy Number.py" "0202. Happy Number.py"
mv "206. Reverse Linked List.py" "0206. Reverse Linked List.py"
mv "242. Valid Anagram.py" "0242. Valid Anagram.py"
mv "3. Longest Substring Without Repeating Characters.py" "0003. Longest Substring Without Repeating Characters.py"
mv "39. Combination Sum.py" "0039. Combination Sum.py"
mv "4. Median of Two Sorted Arrays.py" "0004. Median of Two Sorted Arrays.py"
mv "5. Longest Palindromic Substring.py" "0005. Longest Palindromic Substring.py"
mv "55. Jump Game.py" "0055. Jump Game.py"
mv "724. Pivot Index.py" "0724. Pivot Index.py"
mv "78. Subsets.py" "0078. Subsets.py"
mv "9. Palindrome Number.py" "0009. Palindrome Number.py"
mv "92. Reverse Linked List II.py" "0092. Reverse Linked List II.py"

